version: '3.7'
services:
  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '55432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local